# Generated by Django 6.1 on 2026-09-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_business_account_id", models.CharField(max_length=255)),
                ("phone_number_id", models.CharField(max_length=255, unique=True)),
                ("access_token_env_var", models.CharField(max_length=255)),
                ("webhook_verify_token_env_var", models.CharField(max_length=255)),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_integration",
                        to="businesses.business",
                    ),
                ),
            ],
        ),
    ]
