# Generated by Django 6.1 on 2026-08-16

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Q

import catalog.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("businesses", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="catalog_categories", to="businesses.business")),
            ],
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("item_type", models.CharField(choices=[("product", "Product"), ("service", "Service"), ("subscription", "Subscription"), ("digital_product", "Digital product"), ("membership", "Membership"), ("rental", "Rental")], max_length=30)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(choices=[("USD", "USD"), ("KES", "KES"), ("EUR", "EUR"), ("GBP", "GBP")], default="USD", max_length=3)),
                ("price_note", models.CharField(blank=True, max_length=255)),
                ("availability", models.CharField(choices=[("available", "Available"), ("unavailable", "Unavailable"), ("by_appointment", "By appointment")], default="available", max_length=30)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("current_stock", models.PositiveIntegerField(blank=True, null=True)),
                ("low_stock_threshold", models.PositiveIntegerField(blank=True, null=True)),
                ("warehouse_location", models.CharField(blank=True, max_length=255)),
                ("appointment_required", models.BooleanField(default=False)),
                ("service_duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("customer_information", models.TextField(blank=True)),
                ("faq_items", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="catalog_items", to="businesses.business")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="catalog_items", to="catalog.category")),
            ],
        ),
        migrations.CreateModel(
            name="CatalogMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.ImageField(upload_to=catalog.models.catalog_media_upload_to)),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("is_thumbnail", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("catalog_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="catalog.catalogitem")),
            ],
        ),
        migrations.AddConstraint(model_name="category", constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), models.F("business"), name="unique_catalog_category_name_per_business")),
        migrations.AddConstraint(model_name="catalogitem", constraint=models.UniqueConstraint(condition=~Q(("sku", "")), fields=("business", "sku"), name="unique_catalog_sku_per_business")),
        migrations.AddConstraint(model_name="catalogmedia", constraint=models.UniqueConstraint(condition=Q(("is_thumbnail", True)), fields=("catalog_item",), name="unique_catalog_thumbnail_per_item")),
        migrations.AddIndex(model_name="catalogitem", index=models.Index(fields=["business", "item_type"], name="catalog_c_busi_5dc8a7_idx")),
        migrations.AddIndex(model_name="catalogitem", index=models.Index(fields=["business", "category"], name="catalog_c_busi_7cda60_idx")),
        migrations.AddIndex(model_name="catalogitem", index=models.Index(fields=["business", "availability"], name="catalog_c_busi_5b63df_idx")),
        migrations.AddIndex(model_name="catalogitem", index=models.Index(fields=["business", "created_at"], name="catalog_c_busi_66fe6e_idx")),
    ]
