# Generated by Django 6.1 on 2026-08-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("whatsapp", "WhatsApp"), ("website", "Website"), ("email", "Email"), ("sms", "SMS"), ("facebook", "Facebook"), ("instagram", "Instagram"), ("telegram", "Telegram")], max_length=20)),
                ("participant_address", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("active", "Active"), ("needs_reply", "Needs reply"), ("resolved", "Resolved")], default="active", max_length=20)),
                ("handling_mode", models.CharField(choices=[("ai", "AI"), ("human", "Human")], default="human", max_length=20)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="businesses.business")),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="customers.customer")),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sender_type", models.CharField(choices=[("customer", "Customer"), ("human", "Human"), ("ai", "AI")], max_length=20)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="conversations.conversation")),
            ],
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["business", "last_message_at"], name="conversatio_busines_b39a7f_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["business", "status"], name="conversatio_busines_654e25_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["business", "handling_mode"], name="conversatio_busines_83ac15_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["business", "channel"], name="conversatio_busines_c0024b_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "created_at"], name="conversatio_convers_4b968d_idx"),
        ),
    ]
