# Generated by Django 6.1 on 2026-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_whatsappintegration'),
        ('conversations', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='external_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='processed', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='provider_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'whatsapp'), models.Q(('participant_address', ''), _negated=True)), fields=('business', 'participant_address'), name='unique_whatsapp_participant_per_business'),
        ),
    ]
