# Generated by Django 6.1 on 2026-08-16

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("relationship", models.CharField(choices=[("contact", "Contact"), ("lead", "Lead"), ("customer", "Customer")], default="contact", max_length=20)),
                ("lead_status", models.CharField(blank=True, choices=[("new", "New"), ("cold", "Cold"), ("warm", "Warm"), ("hot", "Hot")], max_length=20)),
                ("source", models.CharField(choices=[("whatsapp", "WhatsApp"), ("website", "Website"), ("email", "Email"), ("sms", "SMS"), ("manual", "Manual"), ("import", "Import"), ("google_contacts", "Google Contacts"), ("other", "Other")], default="manual", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customers", to="businesses.business")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(condition=~Q(("phone", "")), fields=("business", "phone"), name="unique_customer_phone_per_business"),
                    models.UniqueConstraint(condition=~Q(("email", "")), fields=("business", "email"), name="unique_customer_email_per_business"),
                ],
            },
        ),
    ]
