# Generated by Django 6.1 on 2026-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_whatsappintegration'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_e164',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_e164', ''), _negated=True), fields=('business', 'phone_e164'), name='unique_customer_phone_e164_per_business'),
        ),
    ]
