# Generated by Django 6.1 on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q

import ai_employee.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("businesses", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AIEmployeeConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True)),
                ("human_takeover_enabled", models.BooleanField(default=True)),
                ("primary_language", models.CharField(default="English", max_length=30)),
                ("supported_languages", models.JSONField(default=list)),
                ("personality", models.CharField(choices=[("Friendly", "Friendly"), ("Professional", "Professional"), ("Warm", "Warm"), ("Playful", "Playful"), ("Luxury", "Luxury"), ("Technical", "Technical"), ("Casual", "Casual"), ("Formal", "Formal")], default="Friendly", max_length=30)),
                ("communication_style", models.CharField(choices=[("Short & Direct", "Short & Direct"), ("Balanced", "Balanced"), ("Detailed", "Detailed")], default="Balanced", max_length=30)),
                ("emoji_usage", models.CharField(choices=[("Never", "Never"), ("Sometimes", "Sometimes"), ("Often", "Often")], default="Sometimes", max_length=20)),
                ("preferred_tone", models.CharField(choices=[("Helpful", "Helpful"), ("Confident", "Confident"), ("Educational", "Educational"), ("Sales-focused", "Sales-focused"), ("Conversational", "Conversational")], default="Helpful", max_length=30)),
                ("writing_examples", models.TextField(blank=True)),
                ("writing_style_options", models.JSONField(default=dict)),
                ("welcome_message", models.TextField(blank=True)),
                ("away_message", models.TextField(blank=True)),
                ("closing_message", models.TextField(blank=True)),
                ("outside_hours_mode", models.CharField(choices=[("continue", "Continue"), ("collect", "Collect"), ("closed", "Closed")], default="collect", max_length=10)),
                ("max_ai_messages", models.PositiveIntegerField(default=10)),
                ("upsell_products", models.BooleanField(default=True)),
                ("recommend_alternatives", models.BooleanField(default=True)),
                ("close_sales_automatically", models.BooleanField(default=False)),
                ("business_context", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="ai_employee_configuration", to="businesses.business")),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("faq", "FAQ"), ("document", "Document"), ("website", "Website")], max_length=20)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("faq_question", models.TextField(blank=True)),
                ("faq_answer", models.TextField(blank=True)),
                ("faq_category", models.CharField(blank=True, choices=[("General", "General"), ("Pricing", "Pricing"), ("Delivery", "Delivery"), ("Support", "Support"), ("Other", "Other")], max_length=20)),
                ("file", models.FileField(blank=True, null=True, upload_to=ai_employee.models.knowledge_document_upload_to)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_knowledge_sources", to="businesses.business")),
            ],
        ),
        migrations.AddConstraint(
            model_name="knowledgesource",
            constraint=models.UniqueConstraint(condition=Q(("kind", "website"), ~Q(("url", ""))), fields=("business", "url"), name="unique_ai_knowledge_website_per_business"),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(fields=["business", "kind"], name="ai_employee_busines_c8cb52_idx"),
        ),
    ]
