import React from "react";

type AiSummaryCardProps = {
  title?: string;
  bullets?: string[];
  confidence?: number; // 0-100
  lastUpdated?: string;
};

export default function AiSummaryCard({
  title = "AI Conversation Summary",
  bullets = [
    "Asked about internet packages",
    "Interested in Business Package",
    "Waiting for owner's reply",
  ],
  confidence = 72,
  lastUpdated = "Just now",
}: AiSummaryCardProps) {
  return (
    <div className="rounded-3xl border border-[#E5E7EB]/10 bg-white p-4 shadow-[0_8px_24px_rgba(15,23,42,0.04)]">
      <div className="flex items-start justify-between">
        <div>
          <h3 className="text-sm font-semibold text-[#0F172A]">{title}</h3>
          <p className="mt-1 text-xs text-[#64748B]">Summary generated by AI (placeholder)</p>
        </div>
        <div className="text-right">
          <div className="inline-flex items-center gap-2 rounded-full bg-[#F8FAFC] px-3 py-1 text-xs font-semibold text-[#334155]">
            <svg className="h-3 w-3 text-[#334155]" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
              <circle cx="10" cy="10" r="8" stroke="currentColor" strokeWidth="1" />
            </svg>
            {confidence}%
          </div>
          <div className="mt-1 text-[11px] text-[#94A3B8]">Updated {lastUpdated}</div>
        </div>
      </div>

      <ul className="mt-3 list-disc list-inside text-sm text-[#475569] space-y-1">
        {bullets.map((b, i) => (
          <li key={i} className="truncate">
            {b}
          </li>
        ))}
      </ul>

      <div className="mt-4 flex items-center justify-between">
        <div className="text-xs text-[#94A3B8]">Confidence</div>
        <div className="w-36">
          <div className="h-2 w-full rounded-full bg-[#F1F5F9]">
            <div className="h-2 rounded-full bg-[#22C55E]" style={{ width: `${Math.max(0, Math.min(100, confidence))}%` }} />
          </div>
        </div>
      </div>
    </div>
  );
}
